"use client"

import { useState } from "react"
import { Plus, Edit2, Trash2, Calendar as CalendarIcon, Clock, Layers, Filter } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table"
import { format } from "date-fns"
import { toast } from "sonner"

// Hooks & Services
import { 
    useShifts, 
    useRosters, 
    useAssignedRosters, 
    useDeleteShift, 
    useDeleteRoster, 
    useDeleteAssignedRoster 
} from "@/hooks/hr-queries"
import { useStoreContext } from "@/store/use-store-context"

// Components
import { ShiftDialog } from "@/components/hr/shift-dialog"
import { RosterDialog } from "@/components/hr/roster-dialog"
import { AssignmentDialog } from "@/components/hr/assignment-dialog"
import { RosterCalendar } from "@/components/hr/roster-calendar"
import { Shift, Roster } from "@/types/hr"

export function DutyRosterView() {
    const { activeStoreId } = useStoreContext()
    
    // State for Dialogs
    const [shiftOpen, setShiftOpen] = useState(false)
    const [rosterOpen, setRosterOpen] = useState(false)
    const [assignmentOpen, setAssignmentOpen] = useState(false)
    const [selectedShift, setSelectedShift] = useState<Shift | null>(null)
    const [selectedRoster, setSelectedRoster] = useState<Roster | null>(null)
    const [initialAssignmentDate, setInitialAssignmentDate] = useState<string | undefined>()

    // Helper to robustly extract an array
    const getArrayData = (res: any) => {
        if (Array.isArray(res?.data?.data)) return res.data.data
        if (Array.isArray(res?.data)) return res.data
        return []
    }
    
    // Data Queries - Pass branchId but handle existing null records if needed
    const queryParams = { 
        branchId: activeStoreId || undefined, // Use undefined if empty to avoid filtering by ""
        limit: 100 
    }
    const { data: shiftsRes } = useShifts(queryParams)
    const { data: rostersRes } = useRosters(queryParams)
    const { data: assignmentsRes } = useAssignedRosters(queryParams)

    const shifts = getArrayData(shiftsRes)
    const rosters = getArrayData(rostersRes)
    const assignments = getArrayData(assignmentsRes)

    // Mutations
    const deleteShiftMutation = useDeleteShift()
    const deleteRosterMutation = useDeleteRoster()
    const deleteAssignmentMutation = useDeleteAssignedRoster()

    // Handlers
    const handleAddShift = () => {
        setSelectedShift(null)
        setShiftOpen(true)
    }

    const handleEditShift = (shift: Shift) => {
        setSelectedShift(shift)
        setShiftOpen(true)
    }

    const handleAddRoster = () => {
        setSelectedRoster(null)
        setRosterOpen(true)
    }

    const handleAddAssignment = (date?: Date) => {
        setInitialAssignmentDate(date ? format(date, 'yyyy-MM-dd') : undefined)
        setAssignmentOpen(true)
    }

    const handleDelete = async (type: 'shift' | 'roster' | 'assignment', id: string) => {
        if (!window.confirm(`Are you sure you want to delete this ${type}?`)) return
        
        try {
            if (type === 'shift') await deleteShiftMutation.mutateAsync(id)
            else if (type === 'roster') await deleteRosterMutation.mutateAsync(id)
            else await deleteAssignmentMutation.mutateAsync(id)
            toast.success(`${type.charAt(0).toUpperCase() + type.slice(1)} deleted successfully`)
        } catch {
            toast.error(`Failed to delete ${type}`)
        }
    }

    return (
        <div className="space-y-6 print:space-y-0 print:m-0 print:p-0">
            {/* Ultra-Clean Professional Print Header (Pure Text) */}
            <div className="hidden print:flex flex-col items-center text-center mb-2 pb-0 w-full">
                <h1 className="text-4xl font-black uppercase tracking-widest text-black">Patwary General Hospital</h1>
                <div className="flex items-center gap-4 mt-1">
                    <h2 className="text-xl font-bold text-black px-4 py-0.5 border-x-2 border-black">Employee Duty Roster</h2>
                </div>
                <div className="flex justify-center w-full mt-2 text-[10px] font-bold uppercase opacity-60">
                    <span>Generated by HAMOOD TECH IT</span>
                </div>
            </div>

            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 no-print">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-primary/10 rounded-lg">
                        <CalendarIcon className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight">Duty Roster Board</h1>
                        <p className="text-muted-foreground text-sm">Visual scheduling, shift templates, and period management.</p>
                    </div>
                </div>
                <div className="flex flex-wrap gap-2">
                    <Button variant="outline" onClick={handleAddShift}>
                        <Clock className="mr-2 h-4 w-4" />
                        Manage Shifts
                    </Button>
                    <Button variant="outline" onClick={handleAddRoster}>
                        <Layers className="mr-2 h-4 w-4" />
                        New Period
                    </Button>
                    <Button onClick={() => handleAddAssignment()}>
                        <Plus className="mr-2 h-4 w-4" />
                        Assign Shift
                    </Button>
                </div>
            </div>

            <Tabs defaultValue="board" className="space-y-4">
                <TabsList className="bg-muted/50 p-1 no-print">
                    <TabsTrigger value="board" className="flex items-center gap-2">
                        <CalendarIcon className="h-4 w-4" />
                        Roster Board
                    </TabsTrigger>
                    <TabsTrigger value="shifts" className="flex items-center gap-2">
                        <Clock className="h-4 w-4" />
                        Shift Templates
                    </TabsTrigger>
                    <TabsTrigger value="periods" className="flex items-center gap-2">
                        <Layers className="h-4 w-4" />
                        Roster Periods
                    </TabsTrigger>
                </TabsList>

                <TabsContent value="board" className="border-none p-0 outline-none">
                    <RosterCalendar 
                        assignments={assignments}
                        branchId={activeStoreId || ""}
                        onSelectEvent={(asgn) => {
                            if (window.confirm("Do you want to delete this assignment?")) {
                                handleDelete('assignment', asgn.id)
                            }
                        }}
                        onSelectSlot={(slot) => handleAddAssignment(slot.start)}
                    />
                </TabsContent>

                <TabsContent value="shifts" className="space-y-4">
                    <div className="rounded-xl border bg-card shadow-sm overflow-hidden">
                        <Table>
                            <TableHeader>
                                <TableRow className="bg-muted/30 hover:bg-muted/30">
                                    <TableHead>Shift Name</TableHead>
                                    <TableHead>Working Hours</TableHead>
                                    <TableHead>Description</TableHead>
                                    <TableHead className="text-right">Actions</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {shifts.map((shift: any) => (
                                    <TableRow key={shift.id}>
                                        <TableCell className="font-semibold">{shift.name}</TableCell>
                                        <TableCell>
                                            <Badge variant="outline" className="font-mono">
                                                {format(new Date(shift.startTime), "hh:mm a")} - {format(new Date(shift.endTime), "hh:mm a")}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-muted-foreground text-sm">
                                            {shift.description || "-"}
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <div className="flex justify-end gap-2">
                                                <Button variant="ghost" size="icon" onClick={() => handleEditShift(shift)}>
                                                    <Edit2 className="h-4 w-4" />
                                                </Button>
                                                <Button variant="ghost" size="icon" className="text-destructive" onClick={() => handleDelete('shift', shift.id)}>
                                                    <Trash2 className="h-4 w-4" />
                                                </Button>
                                            </div>
                                        </TableCell>
                                    </TableRow>
                                ))}
                                {shifts.length === 0 && (
                                    <TableRow>
                                        <TableCell colSpan={4} className="h-24 text-center">
                                            No shift templates found. Create one to get started.
                                        </TableCell>
                                    </TableRow>
                                )}
                            </TableBody>
                        </Table>
                    </div>
                </TabsContent>

                <TabsContent value="periods" className="space-y-4">
                    <div className="rounded-xl border bg-card shadow-sm overflow-hidden">
                        <Table>
                            <TableHeader>
                                <TableRow className="bg-muted/30 hover:bg-muted/30">
                                    <TableHead>Shift</TableHead>
                                    <TableHead>Start Date</TableHead>
                                    <TableHead>End Date</TableHead>
                                    <TableHead className="text-right">Actions</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {rosters.map((roster: any) => (
                                    <TableRow key={roster.id}>
                                        <TableCell className="font-medium">{roster.shift?.name}</TableCell>
                                        <TableCell>{format(new Date(roster.startDate), "PPP")}</TableCell>
                                        <TableCell>{format(new Date(roster.endDate), "PPP")}</TableCell>
                                        <TableCell className="text-right">
                                            <Button variant="ghost" size="icon" className="text-destructive" onClick={() => handleDelete('roster', roster.id)}>
                                                <Trash2 className="h-4 w-4" />
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))}
                                {rosters.length === 0 && (
                                    <TableRow>
                                        <TableCell colSpan={4} className="h-24 text-center">
                                            No roster periods defined.
                                        </TableCell>
                                    </TableRow>
                                )}
                            </TableBody>
                        </Table>
                    </div>
                </TabsContent>
            </Tabs>

            <ShiftDialog 
                open={shiftOpen} 
                onOpenChange={setShiftOpen} 
                shift={selectedShift}
                onSuccess={() => setShiftOpen(false)}
            />
            <RosterDialog
                open={rosterOpen}
                onOpenChange={setRosterOpen}
                branchId={activeStoreId || ""}
                roster={selectedRoster}
                onSuccess={() => setRosterOpen(false)}
            />
            <AssignmentDialog
                open={assignmentOpen}
                onOpenChange={setAssignmentOpen}
                branchId={activeStoreId || ""}
                initialDate={initialAssignmentDate}
                onSuccess={() => setAssignmentOpen(false)}
            />
        </div>
    )
}
